# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

- task: createbccontainer@4
  inputs:
    containername: 'BC'
    artifactUrl: 'https://bcartifacts.azureedge.net/onprem/14.0.29537.0/w1'
    isolation: 'default'
    fastcontainer: true
- task: CompileBCApps@2
  inputs:
    ContainerName: 'BC'
    Auth: 'Windows'